# Generated by Django 5.0.14 on 2025-05-26 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('is_superuser_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pharmacies', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'MANAGER'}, related_name='managed_pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
